---
- name: Create website directory if not exist
  ansible.builtin.file:
    path: "{{ bac_container_mount_dir }}"
    state: directory
    mode: 0755

- name: Copy website file template
  ansible.builtin.template:
    src: "{{ bac_file_index_template }}"
    dest: "{{ bac_container_mount_dir }}/index.html"
    mode: 0644

- name: Create apache container
  community.docker.docker_container:
    name: "{{ bac_container_name }}"
    image: "httpd:{{ bac_apache_image_version }}"
    state: started
    restart_policy: "always"
    ports:
      - "{{ bac_container_port }}:{{ bac_apache_port }}"
    volumes:
      - "{{ bac_container_mount_dir }}:{{ bac_apache_website_folder }}"
