---
- name: Install some packages
  ansible.builtin.package: name={{ item }} state=present
  with_items:
    - epel-release
    - wget
    - git

- name: install python-pip
  ansible.builtin.yum: name=python-pip state=present update_cache=yes

- name: Install docker python
  ansible.builtin.pip: name=docker state=present
