---
- name: Disable swap temporarily
  command: swapoff -a

- name: Comment out swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '#\1'

- name: Create cri-o.conf file to load the br_netfilter module for cri-o
  copy:
    dest: /etc/modules-load.d/cri-o.conf
    content: |
      br_netfilter

- name: Load the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Create cri-o.conf file for sysctl to enable IPv4 routing
  copy:
    dest: /etc/sysctl.d/cri-o.conf
    content: |
      net.ipv4.ip_forward = 1
  notify: Apply sysctl settings