---
- name: Configure SELinux in permissive mode in current session
  command: setenforce 0
  when: ansible_selinux.status == "enabled"

- name: Configure SELinux in permissive mode in config file
  replace:
    path: /etc/sysconfig/selinux
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=permissive'
  when: ansible_selinux.status == "enabled"

- name: Ensure firewalld is started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: true

- name: Enable Masquerading in firewall permanently
  firewalld:
    zone: public
    masquerade: "true"
    permanent: yes
    immediate: yes
    state: enabled

- name: Authorize cni pod network host port
  firewalld:
    port: "{{ kubernetes_cni_network.pod_host_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  when: kubernetes_cni_network.pod_host_port != ""

- name: Swap cri-o netfilter setup
  include_tasks: swap-crio-netfilter-setup.yml

- name: Install container-selinux
  dnf:
    name: container-selinux
    state: present