---
- name: Ensure dependencies are installed
  apt:
    pkg:
    - apt-transport-https
    - software-properties-common
    - ca-certificates
    - python3
    - curl  
    - ufw
    state: present
    update_cache: yes

- name: Set default firewall incoming rule
  ufw:
    default: deny
    direction: incoming

- name: Set default firewall outgoing rule
  ufw:
    default: allow
    direction: outgoing

- name: Allow ssh incoming rule
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Authorize cni pod network host port
  ufw:
    rule: allow
    port: "{{ kubernetes_cni_network.pod_host_port }}"
    proto: tcp
  when: kubernetes_cni_network.pod_host_port != ""

- name: Enable firewall
  ufw:
    state: enabled

- name: Swap cri-o netfilter setup
  include_tasks: swap-crio-netfilter-setup.yml